import Foundation

enum JockAnimExporter {
    static func export(
        fitResult: RigFitResult,
        clipID: String,
        displayName: String,
        fps: Double,
        looping: Bool,
        to url: URL
    ) throws {
        let durationSeconds = fitResult.frames.last?.timeSeconds ?? 0
        var tracks: [[String: Any]] = []

        for jointName in CanonicalRig.jointNames {
            let translationKeys = fitResult.frames.compactMap { frame -> [String: Any]? in
                guard let p = frame.jointPositions3D[jointName] else { return nil }

                return [
                    "t": frame.timeSeconds,
                    "value": [p.x, p.y, p.z]
                ]
            }

            let rotationKeys = fitResult.frames.compactMap { frame -> [String: Any]? in
                guard let q = frame.localRotationsWXYZ[jointName] else { return nil }

                return [
                    "t": frame.timeSeconds,
                    "value": [q.w, q.x, q.y, q.z]
                ]
            }

            tracks.append([
                "joint": jointName,
                "channel": "translation_xyz_absolute",
                "keys": translationKeys
            ])

            tracks.append([
                "joint": jointName,
                "channel": "rotation_quat_wxyz_absolute",
                "keys": rotationKeys
            ])
        }

        let payload: [String: Any] = [
            "schema": "com.gravitas.jockanim.v0",
            "clip_id": clipID,
            "display_name": displayName,
            "rig_id": CanonicalRig.rigID,
            "rig_version": CanonicalRig.rigVersion,
            "pose_mode": "absoluteLocal",
            "clip_type": "full_body_animation",
            "timing": [
                "fps": fps,
                "duration_seconds": durationSeconds,
                "looping": looping
            ],
            "joints": CanonicalRig.jointNames,
            "tracks": tracks,
            "locomotion": [
                "enabled": false,
                "locomotion_type": "stationary",
                "world_space_motion": "none",
                "recommended_speed_mps": 0.0,
                "root_rotation_degrees": 0.0
            ],
            "transition": [
                "default_transition_frames": 5,
                "transition_fps": fps
            ],
            "tags": [
                "category": ["rotomotion", "draft"],
                "emotion": [],
                "threat": [],
                "story": [],
                "allowed_states": ["debug"]
            ],
            "quality": [
                "approved_for_runtime": false,
                "approved_for_episode": false,
                "debug_only": true
            ],
            "notes": "Generated by Gravitas RotoMotion constrained rig fit. Ground controller used: \(fitResult.frames.contains { $0.groundPlaneApplied })."
        ]

        let data = try JSONSerialization.data(
            withJSONObject: payload,
            options: [.prettyPrinted, .sortedKeys]
        )
        try data.write(to: url, options: .atomic)
    }
}
