import Foundation

enum RotoMotionJockAnimExporter {
    static func makeJockAnimPayload(
        clipID: String,
        displayName: String,
        normalized: NormalizedMeshyPoseCapture?,
        smoothed: SmoothedMeshyPoseCapture?,
        fps: Double
    ) throws -> [String: Any] {
        if let smoothed {
            return try makeFromSmoothed(
                clipID: clipID,
                displayName: displayName,
                smoothed: smoothed,
                fps: fps
            )
        }

        if let normalized {
            return try makeFromNormalized(
                clipID: clipID,
                displayName: displayName,
                normalized: normalized,
                fps: fps
            )
        }

        throw NSError(
            domain: "GravitasRotoMotion",
            code: 7001,
            userInfo: [
                NSLocalizedDescriptionKey: "No normalized or smoothed capture available for JockAnim export."
            ]
        )
    }

    private static func makeFromNormalized(
        clipID: String,
        displayName: String,
        normalized: NormalizedMeshyPoseCapture,
        fps: Double
    ) throws -> [String: Any] {
        let frames = normalized.frames
        let duration = frames.last?.timeSeconds ?? 0
        let tracks = makeTracksFromNormalized(frames: frames)

        return basePayload(
            clipID: clipID,
            displayName: displayName,
            fps: fps,
            duration: duration,
            tracks: tracks,
            sourceKind: "normalized_meshy24"
        )
    }

    private static func makeFromSmoothed(
        clipID: String,
        displayName: String,
        smoothed: SmoothedMeshyPoseCapture,
        fps: Double
    ) throws -> [String: Any] {
        let frames = smoothed.frames
        let duration = frames.last?.timeSeconds ?? 0
        let tracks = makeTracksFromSmoothed(frames: frames)

        return basePayload(
            clipID: clipID,
            displayName: displayName,
            fps: fps,
            duration: duration,
            tracks: tracks,
            sourceKind: "smoothed_meshy24"
        )
    }

    private static func basePayload(
        clipID: String,
        displayName: String,
        fps: Double,
        duration: Double,
        tracks: [[String: Any]],
        sourceKind: String
    ) -> [String: Any] {
        [
            "schema": "com.gravitas.jockanim.v0",
            "clip_id": clipID,
            "display_name": displayName,
            "rig_id": CanonicalRig.rigID,
            "rig_version": CanonicalRig.rigVersion,
            "pose_mode": "absoluteLocal",
            "clip_type": "full_body_animation",
            "source": [
                "kind": sourceKind,
                "generated_by": "Gravitas RotoMotion"
            ],
            "timing": [
                "fps": fps,
                "duration_seconds": duration,
                "looping": false
            ],
            "joints": CanonicalRig.jointNames,
            "tracks": tracks,
            "locomotion": [
                "enabled": false,
                "locomotion_type": "stationary",
                "world_space_motion": "none",
                "recommended_speed_mps": 0,
                "root_rotation_degrees": 0
            ],
            "transition": [
                "default_transition_frames": 5,
                "transition_fps": fps
            ],
            "tags": [
                "category": ["rotomotion", "draft"],
                "emotion": [],
                "threat": [],
                "story": [],
                "allowed_states": ["debug"]
            ],
            "quality": [
                "approved_for_runtime": false,
                "approved_for_episode": false,
                "debug_only": true
            ],
            "notes": "Generated by Gravitas RotoMotion preview package export."
        ]
    }

    private static func makeTracksFromNormalized(
        frames: [NormalizedMeshyPoseCapture.Frame]
    ) -> [[String: Any]] {
        var tracks: [[String: Any]] = []

        for jointName in CanonicalRig.jointNames {
            let translationKeys: [[String: Any]] = frames.compactMap { frame in
                guard let joint = frame.joints[jointName],
                      !joint.missing else {
                    return nil
                }

                return [
                    "t": frame.timeSeconds,
                    "value": [
                        joint.x - 0.5,
                        0.0,
                        joint.y - 0.5
                    ]
                ]
            }

            let rotationKeys: [[String: Any]] = frames.map { frame in
                [
                    "t": frame.timeSeconds,
                    "value": [0.0, 0.0, 0.0]
                ]
            }

            tracks.append([
                "joint": jointName,
                "channel": "translation_xyz_absolute",
                "keys": translationKeys
            ])

            tracks.append([
                "joint": jointName,
                "channel": "rotation_euler_xyz_radians",
                "keys": rotationKeys
            ])
        }

        return tracks
    }

    private static func makeTracksFromSmoothed(
        frames: [SmoothedMeshyPoseCapture.Frame]
    ) -> [[String: Any]] {
        var tracks: [[String: Any]] = []

        for jointName in CanonicalRig.jointNames {
            let translationKeys: [[String: Any]] = frames.compactMap { frame in
                guard let joint = frame.joints[jointName],
                      !joint.missing else {
                    return nil
                }

                return [
                    "t": frame.timeSeconds,
                    "value": [
                        joint.smoothedX - 0.5,
                        0.0,
                        joint.smoothedY - 0.5
                    ]
                ]
            }

            let rotationKeys: [[String: Any]] = frames.map { frame in
                [
                    "t": frame.timeSeconds,
                    "value": [0.0, 0.0, 0.0]
                ]
            }

            tracks.append([
                "joint": jointName,
                "channel": "translation_xyz_absolute",
                "keys": translationKeys
            ])

            tracks.append([
                "joint": jointName,
                "channel": "rotation_euler_xyz_radians",
                "keys": rotationKeys
            ])
        }

        return tracks
    }
}
